### ISSUE TITLE
Where is the original driver code?

### ISSUE THREAD

**Issue by sholladay** [RebirthDB/rebirthdb-js#19]
I was a little surprised to see this is now a fork of `rethinkdbdash`. The code I'm using from npm is a completely different codebase. Where did the original repo go?

**Comment by thelinuxlich** [comment]
Hi Seth! When we forked RethinkDB as RebirthDB, the initial idea was to adopt rethinkdbdash as the official Javascript driver, but the amazing @ronzeidman stepped in and created a Typescript driver which we advocate as the official Javascript driver now.

**Comment by sholladay** [comment]
Aloha! Yes, we're trying to switch to @ronzeidman's TS driver, but we hit a couple of things that work differently, and I was hoping to look at the source for the original driver to aid in some debugging / design decisions. Assuming the original driver did not use a build process, I can probably get what I need by unpacking the tarball from npm. Still, the repo with commit history ought to be archived somewheres, IMO, at least until its usage has dropped significantly. If anyone has a copy of it, please send it to me.

**Comment by ronzeidman** [comment]
https://github.com/rethinkdb/rethinkdb-legacy/tree/next/drivers/javascript
This is the original drivers code
